export const MAX_ALLOWED_GUESSES_AMOUNT = 5;
export const HOURS_IN_SINGLE_DAY = 24;
export const MILLISECONDS_IN_AN_HOUR = 1000 * 60 * 60;
export const MILLISECONDS_IN_A_DAY = MILLISECONDS_IN_AN_HOUR * 24;
